version: '3.2'

networks:
    default:
        external:
          name: iae_network
services:
    db:
        image: postgres
        volumes:
            - prod_db_data:/var/lib/postgresql/data
        env_file: .env
    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: iae:p1.0
        depends_on:
            - db
        ports:
            - 3000:3000
        volumes:
            - .:/app
            - prod_node_modules:/app/node_modules
        env_file: .env
volumes:
    prod_db_data:
    prod_node_modules:
