version: '3.2'

networks:
    default:
        external:
          name: iae_network
services:
    redis:
        image: redis
        command: redis-server
        ports: 
            - 6379:6379
        volumes:
            - redis:/data
        restart: always
    sidekiq:
        image: iae:p1.3
        depends_on:
            - redis
        command: bundle exec sidekiq
        volumes:
          - .:/app
          - iae_uploads:/app/public/uploads
        env_file: .env
        restart: always
    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: iae:p1.3
        depends_on:
            - redis
        ports:
            - 3002:3000
        volumes:
            - .:/app
            - node_modules:/app/node_modules
            - iae_uploads:/app/public/uploads
        env_file: .env
        entrypoint: ./entrypoints/docker-entrypoint.sh
        restart: always
volumes:
    node_modules:
    redis:
    iae_uploads:
        external: true
